// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw-BgaL9mJ_5OJSPke_0iJ-jUWxbhCgOM',
    appId: '1:1012571195233:web:1877da12574aa02a1d2720',
    messagingSenderId: '1012571195233',
    projectId: 'softinsa-badges-ruben',
    authDomain: 'softinsa-badges-ruben.firebaseapp.com',
    storageBucket: 'softinsa-badges-ruben.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa64adBoDC_9QB4eqSBLQ86bJTC8ixkE4',
    appId: '1:1012571195233:android:b9f03414608656751d2720',
    messagingSenderId: '1012571195233',
    projectId: 'softinsa-badges-ruben',
    storageBucket: 'softinsa-badges-ruben.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7g-1OY--apLJAOEtNBz7n7tc8SBAhca4',
    appId: '1:1012571195233:ios:0b3404def813ddc91d2720',
    messagingSenderId: '1012571195233',
    projectId: 'softinsa-badges-ruben',
    storageBucket: 'softinsa-badges-ruben.firebasestorage.app',
    iosBundleId: 'com.example.projetoPdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7g-1OY--apLJAOEtNBz7n7tc8SBAhca4',
    appId: '1:1012571195233:ios:0b3404def813ddc91d2720',
    messagingSenderId: '1012571195233',
    projectId: 'softinsa-badges-ruben',
    storageBucket: 'softinsa-badges-ruben.firebasestorage.app',
    iosBundleId: 'com.example.projetoPdm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw-BgaL9mJ_5OJSPke_0iJ-jUWxbhCgOM',
    appId: '1:1012571195233:web:1f08bf77adf5bf581d2720',
    messagingSenderId: '1012571195233',
    projectId: 'softinsa-badges-ruben',
    authDomain: 'softinsa-badges-ruben.firebaseapp.com',
    storageBucket: 'softinsa-badges-ruben.firebasestorage.app',
  );
}
